### ISSUE TITLE
Decrypt message lost the space and replace with "s"

### ISSUE THREAD

**Issue by Winthan** [kevinselwyn/vernam#1]
The message turns into small letter and space is replaced with "s", can it be fix?

**Comment by kevinselwyn** [comment]
This program converts all messages to lowercase and encodes/decodes only the letters [a-z]. If you have a message with any other characters, like a space, it will not be encoded/decoded.

**Comment by Winthan** [comment]
the problem is "space" is converted into "s" letter for some reason.  Like you said, it should not be encoded into "s" characters at all.
